### PR TITLE
Replace InitialConditionSolver Fortran subroutines with C++

### PR DESCRIPTION
**Pull request by mirenradia**
Pretty much as in the title. Note that I have only removed the Fortran calls in SetLevelData.cpp and have not modified the ones in VariableCoeffPoissonOperator* (other than running clang-format). Note that there is a slight change in the definition of quantities:
- Before: `GETRHOGRADPHIF` calculated 0.5 * \delta^{ij} d_i phi d_j phi
- After: `get_grad_phi_sq` calculates \delta^{ij} d_i phi d_j phi

I have also slightly modified the HDF5 comparison tool to allow comparing of values in an HDF5 checkpoint file within a certain tolerance. Using this tool, I have verified that the checkpoint files produced (with a slightly modified version of the default parameter file) before and after this change have value agreement within 4.0e-15.

### CODE REVIEW

**Comment by KAClough** [comment]
This looks great - I am happy with these changes, they all make sense.

There is one thing that I was thinking of changing that is related to how I wrote the code originally, and so we can do it as a separate pull request if you prefer. I would like get_m() to be get_rho() and to include the gradient energy of the field. get_m is not very descriptive and it would be nice to have the whole energy density in one place, so that it can be easily replaced for other matter types. What do you think?

**Comment by mirenradia** [comment]
> There is one thing that I was thinking of changing that is related to how I wrote the code originally, and so we can do it as a separate pull request if you prefer. I would like get_m() to be get_rho() and to include the gradient energy of the field. get_m is not very descriptive and it would be nice to have the whole energy density in one place, so that it can be easily replaced for other matter types. What do you think?

Yes, I think that would be much clearer and a separate pull request would be a good idea.

**Comment by eugenealim** [comment]
This looks good. Thanks! 

>have not modified the ones in VariableCoeffPoissonOperator*

If you are planning to do this, let me know -- there are some overloads I want to put in to make use of some of the solvers that are written in but never use.

**Comment by mirenradia** [comment]
> If you are planning to do this, let me know -- there are some overloads I want to put in to make use of some of the solvers that are written in but never use.

It wasn't a plan of mine. I can see that @JCAurre has been playing around with higher order stencils in there though. Was this what you wanted to use the overloads for or was it something else?

**Comment by KAClough** [comment]
> > There is one thing that I was thinking of changing that is related to how I wrote the code originally, and so we can do it as a separate pull request if you prefer. I would like get_m() to be get_rho() and to include the gradient energy of the field. get_m is not very descriptive and it would be nice to have the whole energy density in one place, so that it can be easily replaced for other matter types. What do you think?
> 
> Yes, I think that would be much clearer and a separate pull request would be a good idea.

Ok, then I will approve these changes.

**Review by KAClough — APPROVED** [review]

**Comment by KAClough** [comment]
I've approved, but I will leave it for @JCAurre to merge it, since he's now in charge of ICs and probably wants to look over the changes.

**Comment by JCAurre** [comment]
I'm in the airport right now, I can look at them as soon as I get home.
These changes are what you showed me in Atpesc right @miren?

K Clough <notifications@github.com> igorleak hau idatzi zuen (2019 abu. 29,
Osg 16:28):

**Comment by mirenradia** [comment]
> I'm in the airport right now, I can look at them as soon as I get home. These changes are what you showed me in Atpesc right @miren? 

More or less...

**Comment by KAClough** [comment]
There's no rush, @JCAurre :-)

**Comment by eugenealim** [comment]
> It wasn't a plan of mine. I can see that @JCAurre has been playing around with higher order stencils in there though. Was this what you wanted to use the overloads for or was it something else?

No, it has to do with the smoothing routing between relaxation cycles. if you look at the /lib/src/AMRElliptic/AMRPoissonOP.cpp, the smoothing is hardcoded to Gauss-Seidal-Red/Blue

31 int AMRPoissonOp::s_relaxMode = 1; // 1: GSRB; 4: Jacobi

But if you look at the implementation of the AMRPoissonOp (and its descendants, including VariableCoeffPoissonOperator), there are code written already for Jacobi. The "proper" way to fix this is on Chombo side of course, but if we don't want to touch the chombo code, we can overload the AMRPoissonOP::relax function (sorry, not C++ operator, but math operator, we need more words) in VariableCoeffPoissonOperator. I did this in my local copy, but haven't pushed yet since i am still trying to figure out some other stuff.

**Comment by eugenealim** [comment]
p.s. there are reasons to use non-GSRB because the way GSRB is coded at the moment sorta works only for Order 2 stencils.

**Pull request merged**
